services:
  s-ui:
    build: .
    image: s-ui-plus:local
    container_name: s-ui-plus
    hostname: "s-ui-plus"
    network_mode: host
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    entrypoint: "./entrypoint.sh"
